apiVersion: v1
kind: Secret
metadata:
  name: postgres-dev
  labels:
    app: postgres
  type: Opaque
  data:
    POSTGRES_DB: JwBwAG8AcwB0AGcAcgBlAHMAJwA=
    POSTGRES_USER: JwBwAG8AcwB0AGcAcgBlAHMAJwA=
    POSTGRES_PASSWORD: JwBxAHcAZQByAHQAeQAnAA==